### PR TITLE
i18n apply discount code

### LINKED ISSUE #1662: Italian Translation Issue - Apostrophe Causes JS Error When Applying Discount Code
**Describe the bug**
The Italian translation has an apostrophe in the string 'Il codice <strong>%s</strong> è stato applicato all'ordine.' which results in a JS error when applying a discount code. 

**To Reproduce**
1. Set your default language to Italian
2. Apply a discount code by entering it in the field and hitting 'Apply'. 
3. You will get an error in the console containing a formatting error. 

**Screenshots**
image

**Expected behavior**
No errors should occur when applying a discount code. 

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
- PMPro 2.5.9.1
- WP 5.7

**Fix**

The string needs to be changed to `Il codice <strong>%s</strong> è stato applicato all\'ordine.`

### PR DESCRIPTION
**Pull request by mircobabini**
### All Submissions:

* [x] Have you followed the [Contributing guideline](https://github.com/strangerstudios/paid-memberships-pro/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/strangerstudios/paid-memberships-pro/pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fix to applydiscountcode.php where javascript is written by php and not always escaped with _pmpro_no_quotes_. This where causing issues with i18n as reported in the issue below.

Resolves #1662.

### How to test the changes in this Pull Request:

1. Check the linked issue which contains the explanation.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you successfully run tests with your changes locally?

### CODE REVIEW

File: services/applydiscountcode.php [hunk 1]
```diff
@@ -136,11 +136,11 @@
 			if ( count( $code_levels ) <= 1 ) {
 				$code_level = empty( $code_levels ) ? null : $code_levels[0];
 				?>
-				jQuery('#pmpro_level_cost').html('<p><?php printf(__('The <strong>%s</strong> code has been applied to your order.', 'paid-memberships-pro' ), $discount_code);?></p><p><?php echo pmpro_no_quotes(pmpro_getLevelCost( $code_level, array('"', "'", "\n", "\r")))?><?php echo pmpro_no_quotes(pmpro_getLevelExpiration( $code_level, array('"', "'", "\n", "\r")))?></p>');
+				jQuery('#pmpro_level_cost').html('<p><?php pmpro_no_quotes(sprintf(__('The <strong>%s</strong> code has been applied to your order.', 'paid-memberships-pro' ), $discount_code), array('"', "'", "\n", "\r"));?></p><p><?php echo pmpro_no_quotes(pmpro_getLevelCost( $code_level), array('"', "'", "\n", "\r"))?><?php echo pmpro_no_quotes(pmpro_getLevelExpiration( $code_level), array('"', "'", "\n", "\r"))?></p>');
```
Comment (sc0ttkclark) [inline services/applydiscountcode.php:139]:
```suggestion
				jQuery('#pmpro_level_cost').html('<p><?php echo esc_js( sprintf(__( 'The <strong>%s</strong> code has been applied to your order.', 'paid-memberships-pro' ), $discount_code ) );?></p><p><?php echo esc_js( pmpro_getLevelCost( $code_level ) )?><?php echo esc_js( pmpro_getLevelExpiration( $code_level ) ); ?></p>');
```

File: services/applydiscountcode.php [hunk 2]
```diff
@@ -136,11 +136,11 @@
...
 				<?php
 			} else {
 				?>
-				jQuery('#pmpro_level_cost').html('<p><?php printf(__('The <strong>%s</strong> code has been applied to your order.', 'paid-memberships-pro' ), $discount_code);?></p><p><?php echo pmpro_no_quotes(pmpro_getLevelsCost($code_levels), array('"', "'", "\n", "\r"))?><?php echo pmpro_no_quotes(pmpro_getLevelsExpiration($code_levels), array('"', "'", "\n", "\r"))?></p>');
+				jQuery('#pmpro_level_cost').html('<p><?php pmpro_no_quotes(sprintf(__('The <strong>%s</strong> code has been applied to your order.', 'paid-memberships-pro' ), $discount_code), array('"', "'", "\n", "\r"));?></p><p><?php echo pmpro_no_quotes(pmpro_getLevelsCost($code_levels), array('"', "'", "\n", "\r"))?><?php echo pmpro_no_quotes(pmpro_getLevelsExpiration($code_levels), array('"', "'", "\n", "\r"))?></p>');
```
Comment (sc0ttkclark) [inline services/applydiscountcode.php:143]:
```suggestion
				jQuery('#pmpro_level_cost').html('<p><?php echo esc_js( sprintf(__( 'The <strong>%s</strong> code has been applied to your order.', 'paid-memberships-pro' ), $discount_code ) ); ?></p><p><?php echo esc_js( pmpro_getLevelsCost( $code_levels ) ); ?><?php echo esc_js( pmpro_getLevelsExpiration( $code_levels ) ); ?></p>');
```

**Review by sc0ttkclark — COMMENTED** [review]
@mircobabini Can you retest with the esc_js changes I've suggested?

**Review by mircobabini — COMMENTED** [review]
Works great! Thank you @sc0ttkclark, nice usage of `esc_js`.

**Review by sc0ttkclark — CHANGES_REQUESTED** [review]
@ideadude This one needs a little more thought because the esc_js will cause entities for the HTML in the <strong> tags

File: services/applydiscountcode.php [hunk 3]
```diff
@@ -136,11 +136,11 @@
 			if ( count( $code_levels ) <= 1 ) {
 				$code_level = empty( $code_levels ) ? null : $code_levels[0];
 				?>
-				jQuery('#pmpro_level_cost').html('<p><?php printf(__('The <strong>%s</strong> code has been applied to your order.', 'paid-memberships-pro' ), $discount_code);?></p><p><?php echo pmpro_no_quotes(pmpro_getLevelCost( $code_level, array('"', "'", "\n", "\r")))?><?php echo pmpro_no_quotes(pmpro_getLevelExpiration( $code_level, array('"', "'", "\n", "\r")))?></p>');
+				jQuery('#pmpro_level_cost').html('<p><?php echo esc_js( sprintf(__( 'The <strong>%s</strong> code has been applied to your order.', 'paid-memberships-pro' ), $discount_code ) ); ?></p><p><?php echo esc_js( pmpro_getLevelCost( $code_level ) ); ?><?php echo esc_js( pmpro_getLevelExpiration( $code_level ) ); ?></p>');
```
Comment (sc0ttkclark) [inline services/applydiscountcode.php:139]:
```suggestion
				jQuery('#pmpro_level_cost').html('<p><?php printf( esc_attr__( 'The <strong>%s</strong> code has been applied to your order.', 'paid-memberships-pro' ), $discount_code ); ?></p><p><?php echo esc_js( pmpro_getLevelCost( $code_level ) . pmpro_getLevelExpiration( $code_level ) ); ?></p>');
```

**Comment by sc0ttkclark** [comment]
I'll follow up on this PR to fix the escaping problem

**Comment by mircobabini** [comment]
@sc0ttkclark right. We must use `addslashes`.

```
  | original > Testo con un'apostrofo <strong>dove non andrebbe messo</strong>.
  | esc_js > Testo con un\'apostrofo &lt;strong&gt;dove non andrebbe messo&lt;/strong&gt;.
  | esc_html > Testo con un&#039;apostrofo &lt;strong&gt;dove non andrebbe messo&lt;/strong&gt;.
  | esc_attr > Testo con un&#039;apostrofo &lt;strong&gt;dove non andrebbe messo&lt;/strong&gt;.
  | esc_sql > Testo con un\'apostrofo <strong>dove non andrebbe messo</strong>. <<< this one works!
  | addslashes > Testo con un\'apostrofo <strong>dove non andrebbe messo</strong>. <<< this one works!
```

These are some tests on a string with apostrophe and html tags. The last one is what we want.

**Comment by sc0ttkclark** [comment]
@mircobabini after further digging on this -- the combination of needs here for escaping, but keeping HTML, and removing line breaks so it won't break JS necessitates usage of `wp_json_encode`. I cleaned up this section of the code so it's easier to maintain and easier to see what's going on and why in https://github.com/strangerstudios/paid-memberships-pro/pull/1679
