### PR TITLE
[BUGFIXING] Membership Expiring Email Displays Incorrect Membership Level Name with Multiple Levels

### LINKED ISSUE #3346: Membership Expiring Email Displays Incorrect Membership Level Name with Multiple Levels
**Describe the bug**
When a member has two membership levels, the "Membership Expiring" email incorrectly displays the name of the wrong membership level. Specifically, the `!!membership_level_name!!` placeholder pulls in the incorrect level name (e.g., "Membership 2" instead of "Membership 1"). The `!!enddate!!` placeholder functions as expected and shows the correct expiration date.

**To Reproduce**
1. Assign two membership levels to a single member.
2. Trigger the "Membership Expiring" email for the latest membership levels.
3. Observe that the `!!membership_level_name!!` placeholder displays the wrong membership level name.
4. Verify that the `!!enddate!!` placeholder is displaying the correct expiration date.

**Screenshots**
Image
Image

**Expected behavior**
The "Membership Expiring" email should correctly display the membership level name associated with the expiring membership. The `!!membership_level_name!!` placeholder should reflect the correct level name.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
WordPress Version: 6.7.2
PHP Version: 7.4.33
Paid Memberships Pro: v3.4.2
Tested with Paid Memberships Pro: v3.4.3
Server: Apache/2.4.59 (Debian)
Site Language: en_GB
User Language: en_GB
Timezone: Europe/London
HTTPS Status: true
Multisite: false
User Registration: 0
Blog Public: 1
Default Comment Status: undefined
Environment Type: production
User Count: 3,794
Dotorg Communication: true
```
</details>

### PR DESCRIPTION
**Pull request by MaximilianoRicoTabo**
### All Submissions:

* [x] Have you followed the [Contributing guideline](https://github.com/strangerstudios/paid-memberships-pro/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/strangerstudios/paid-memberships-pro/pulls) for the same update/change?

### Changes proposed in this Pull Request:

Rely on passed by param membership id to retrieve level name inserted to email data.

Resolves #3346 

### How to test the changes in this Pull Request:

Follow steps in the issue above

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### CODE REVIEW

File: classes/email-templates/class-pmpro-email-template-membership-expired.php [hunk 1]
```diff
@@ -138,9 +138,10 @@ public static function get_email_template_variables_with_description() {
 	 */
 	public function get_email_template_variables() {
 		global $wpdb;
+		$membership_level_id = $this->membership_level_id;
```
Comment (andrewlimaza) [inline classes/email-templates/class-pmpro-email-template-membership-expired.php:141]: This line is what fixes the issue, I wanted to share this as this PR now does a bit of refactoring and I myself was confused to where the actual fix was.
