### PR TITLE
Discount codes with unsupported billing details are not highlighted

### LINKED ISSUE #2823: Discount codes with unsupported billing details are not highlighted
**Describe the bug**
If a site has a discount code with unsupported billing details (ex. cycle periods of longer than 1 year while using Stripe), a message will show on the Discount Codes list table:
`The billing details for some of your discount codes are not supported by your gateway. The discount codes with issues are highlighted below.`

The issue is that discount codes with an error are not actually highlighted.

**To Reproduce**
1. Create a new discount code with a billing period of 2 years.
2. Change your gateway to Stripe.
3. Visit the Discount Codes settings page and see that the message is shown, but the discount code is not highlighted.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by MaximilianoRicoTabo**
* Override single_row function to add error class if the discount code row need to be higlighted due miscounfiguration

image

### All Submissions:

* [x] Have you followed the [Contributing guideline](https://github.com/strangerstudios/paid-memberships-pro/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/strangerstudios/paid-memberships-pro/pulls) for the same update/change?

### Changes proposed in this Pull Request:

Override single_row function to add error class if the discount code row need to be higlighted due miscounfiguration

Resolves #2823

### How to test the changes in this Pull Request:

Steps in the linked issue.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### CODE REVIEW

**Review by dparker1005 — APPROVED** [review]

**Review by andrewlimaza — APPROVED** [review]

File: classes/class-pmpro-discount-code-list-table.php [hunk 1]
```diff
@@ -561,5 +561,19 @@ public function column_levels( $item ) {
...
+	/**
+	 * Override single_row function to add error class if the discount code row need to be higlighted due miscounfiguration
+	 *
+	 * @param StdClass $item The current row item.
+	 * @return void
+	 * @since TBD
+	 */
+	public function single_row( $item ) {
+		$cssClass = ( ! pmpro_check_discount_code_for_gateway_compatibility( $item ) ) ? 'pmpro_error' : '';
+		echo '<tr class="' . $cssClass . '">';
```
Comment (ideadude) [inline classes/class-pmpro-discount-code-list-table.php:574]:
```suggestion
		echo '<tr class="' . esc_attr( $cssClass ) . '">';
```
