### PR TITLE
Fix/email confirmation message wpautop

### LINKED ISSUE #2022: "Message Confirmation" visual editor strips paragraph or break tags in Email Confirmation sent to a member
**Describe the bug**
Text added to the message confirmation area of the edit level settings page shows in the email confirmation sent to a member without the paragraphs added in visual mode.

**To Reproduce**
1. Go to the Edit Level Settings page for any membership level
2. Add two sentences with two paragraphs to the editor in "Visual Mode"
3. Save, and send a test email confirmation template or checkout on this level
4. See the sentence in the email sent to the member outputted as one paragraph instead of two

**Screenshots**
Screen Shot 2022-04-11 at 11 45 29

Screen Shot 2022-04-11 at 11 37 24

**Expected behavior**
Paragraphs should not be stripped in the email. if you switch to a text editor, however (screenshot below), then save without switching back to visual, the first paragraph is not stripped in the email.
Screen Shot 2022-04-11 at 12 31 20

Screen Shot 2022-04-11 at 12 27 36

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
- WordPress Version | 5.9.3
- Memberlite Version | 4.5.2
- PHP version | 7.4.28
- Paid Memberships Pro | Version 2.7.5
</details>

### PR DESCRIPTION
**Pull request by mircobabini**
### All Submissions:

* [x] Have you followed the [Contributing guideline](https://github.com/strangerstudios/paid-memberships-pro/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/strangerstudios/paid-memberships-pro/pulls) for the same update/change?

### Changes proposed in this Pull Request:

Resolves #2022.

Also clean up some useless global references (thanks PHPStorm static analyzer) and declare class properties.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you successfully run tests with your changes locally?

### CODE REVIEW

File: classes/class.pmproemail.php [hunk 1]
```diff
@@ -264,13 +297,12 @@ function sendCheckoutEmail($user = NULL, $invoice = NULL)
 			$this->data = array(
 								"subject" => $this->subject, 
 								"name" => $user->display_name, 
-								"display_name" => $user->display_name,
```
Comment (dparker1005) [inline classes/class.pmproemail.php:267]: We should probably keep this email template variable in case live sites are already using it.

File: classes/class.pmproemail.php [hunk 2]
```diff
@@ -1,10 +1,43 @@
...
+		 */
+		public $subject;
+
+		/**
+		 * @var string
+		 */
+		public $template;
+
+		/**
+		 * @var string
```
Comment (dparker1005) [inline classes/class.pmproemail.php:30]:
```suggestion
		 * @var array
```

File: classes/class.pmproemail.php [hunk 3]
```diff
@@ -1,10 +1,43 @@
...
+		public $data;
+
+		/**
+		 * @var string
+		 */
+		public $body;
+
+
+		function __construct() {
 		}
```
Comment (dparker1005) [inline classes/class.pmproemail.php:41]:
```suggestion
```

File: classes/class.pmproemail.php [hunk 4]
```diff
@@ -264,13 +297,12 @@ function sendCheckoutEmail($user = NULL, $invoice = NULL)
...
 								"subject" => $this->subject, 
 								"name" => $user->display_name, 
-								"display_name" => $user->display_name,
 								"user_login" => $user->user_login,
 								"sitename" => get_option("blogname"),
 								"siteemail" => pmpro_getOption("from_email"),
 								"membership_id" => $user->membership_level->id,
 								"membership_level_name" => $user->membership_level->name,
-								"membership_level_confirmation_message" => $confirmation_message,
+								"membership_level_confirmation_message" => wpautop( $confirmation_message ),
```
Comment (dparker1005) [inline classes/class.pmproemail.php:305]: We may instead want to use the `pmpro_confirmation_message` filter which will `wpautop()` the message and let add ons filter it. Here is how we use that filter to display the confirmation message on the confirmation page:
https://github.com/strangerstudios/paid-memberships-pro/blob/1cbc4daf1a8977d2c9d9887ec84adac83c02a0c1/pages/confirmation.php#L48-L54

```suggestion
								"membership_level_confirmation_message" => apply_filters( 'pmpro_confirmation_message', $confirmation_message, $invoice ),
```

**Review by dparker1005 — COMMENTED** [review]
Definitely like declaring the PMProEmail variables at the top of the class! Just a couple of decisions to think about and then should be good to go

**Review by andrewlimaza — CHANGES_REQUESTED** [review]
I agree with @dparker1005 here, we will need these changes done to merge this in.

File: classes/class.pmproemail.php (hunk 1 above)
Comment (mircobabini) [reply classes/class.pmproemail.php:267]: Sure thing, but it's duplicated. The display_name key is already at the end of that array of data.

Comment (mircobabini) [reply classes/class.pmproemail.php]: Merged from dev resolving this redundant key https://github.com/strangerstudios/paid-memberships-pro/pull/2060/commits/c54b9ebef6fe0934cacb59156f52c9c848c6bd21

**Comment by mircobabini** [comment]
Changes applied, dev merged in.

**Review by dparker1005 — APPROVED** [review]

File: classes/class.pmproemail.php [hunk 5]
```diff
@@ -486,7 +517,7 @@ function sendCheckoutEmail($user = NULL, $invoice = NULL)
 								'siteemail' => pmpro_getOption('from_email'),
 								'membership_id' => $membership_level->id,
 								'membership_level_name' => $membership_level->name,
-								'membership_level_confirmation_message' => $confirmation_message,
+								'membership_level_confirmation_message' => apply_filters( 'pmpro_confirmation_message', $confirmation_message, $invoice ),
```
Comment (dparker1005) [inline classes/class.pmproemail.php:520]:
```suggestion
								'membership_level_confirmation_message' => wpautop( $confirmation_message ),
```

**Review by dparker1005 — APPROVED** [review]
Reverting back to explicitly using `wpautop()`. Using `pmpro_confirmation_message` could cause some Add Ons to add information to emails twice, which would be a breaking change. We can consider using that filter in 3.0.
