### PR TITLE
Replace !empty() check with isset() for decimal option

### LINKED ISSUE #1731: Function pmpro_round_price does not set decimals correctly if currency decimals is zero
**Describe the bug**
When using `pmpro_round_price` the price is not rounded correctly when the specified currency has `0` (zero) decimals.

**To Reproduce**
1. Create a custom function that hooks into the `pmpro_checkout_level` filter
2. add `var_dump( pmpro_round_price( 575.34, 'JPY' ) );`
3. Test on PMPro checkout page
4. See error: returns `float 575.34` instead of the expected 575 as Japanese Yen has 0 (zero) decimals.

**Expected behavior**
Prices are correctly rounded according to specified decimals, as per global variable `$pmpro_currencies`, for the currency.
Instead of `empty` we could consider using `isset` to check if the variable contains a decimal value here:
https://github.com/strangerstudios/paid-memberships-pro/blob/8ef6b647db1992ba4d41c3913672b7bba021f8e4/includes/functions.php#L3077

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by sc0ttkclark**
### All Submissions:

* [x] Have you followed the [Contributing guideline](https://github.com/strangerstudios/paid-memberships-pro/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/strangerstudios/paid-memberships-pro/pulls) for the same update/change?

### Changes proposed in this Pull Request:

Resolves #1731.

### How to test the changes in this Pull Request:

1. Have a currency set that uses 0 decimals
2. Attempt to round price
3. See the rounded price has decimals still set

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Fix problem where `pmpro_round_price()` would not take into account currencies with decimals set to 0.

### CODE REVIEW

**Comment by sc0ttkclark** [comment]
Noting: This was the only place in the file and the whole plugin where this logic was using `! empty()` instead of `isset()`

**Review by dparker1005 — APPROVED** [review]

File: includes/functions.php [hunk 1]
```diff
@@ -3074,7 +3074,7 @@ function pmpro_round_price( $price, $currency = '' ) {
 
 	if ( ! empty( $pmpro_currencies[ $currency ] )
 		&& is_array( $pmpro_currencies[ $pmpro_currency ] )
```
Comment (sc0ttkclark) [inline includes/functions.php:3076]:
```suggestion
		&& is_array( $pmpro_currencies[ $currency ] )
```
