### PR TITLE
User registered date is now shown in local time.

### LINKED ISSUE #1665: Members list shows registered date in UTC time
**Describe the bug**
WordPress saves the `user_registered` date in the database in UTC time. When we take that date and show it in the members list, we are not converting it to the local timezone which can make the date appear a day off.

**Expected behavior**
The "Registered" date should show in local time.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Please share non-sensitive information about your hosting environment such as WordPress version, PHP version, Paid Memberships Pro and any related plugins versions.
```
</details>

### PR DESCRIPTION
**Pull request by dparker1005**
### All Submissions:

* [x] Have you followed the [Contributing guideline](https://github.com/strangerstudios/paid-memberships-pro/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/strangerstudios/paid-memberships-pro/pulls) for the same update/change?

### Changes proposed in this Pull Request:
Convert `user_registered` time from GMT to local when showing in reports.

Resolves #1665 .

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### CODE REVIEW

File: adminpages/dashboard.php [hunk 1]
```diff
@@ -244,7 +244,7 @@ function pmpro_dashboard_report_recent_members_callback() {
     						</strong>
     					</td>
     					<td><?php esc_attr_e( $auser->membership ); ?></td>
-    					<td><?php echo date_i18n( get_option( 'date_format' ), strtotime( $theuser->user_registered, current_time( 'timestamp' ) ) ); ?></td>
+    					<td><?php echo date_i18n( get_option( 'date_format' ), strtotime( get_date_from_gmt( $theuser->user_registered, 'Y-m-d H:i:s' ), current_time( 'timestamp' ) ) ); ?></td>
```
Comment (sc0ttkclark) [inline adminpages/dashboard.php:247]: Removing format argument that matches the default argument value.

```suggestion
    					<td><?php echo date_i18n( get_option( 'date_format' ), strtotime( get_date_from_gmt( $theuser->user_registered ), current_time( 'timestamp' ) ) ); ?></td>
```

File: adminpages/reports/login.php [hunk 2]
```diff
@@ -228,7 +228,7 @@ function pmpro_report_login_page()
 								<?php echo $theuser->display_name;?>
 							</td>
 							<td><?php echo $auser->membership?></td>												
-							<td><?php echo date_i18n("m/d/Y", strtotime($theuser->user_registered, current_time("timestamp")))?></td>
+							<td><?php echo date_i18n("m/d/Y", strtotime( get_date_from_gmt( $theuser->user_registered, 'Y-m-d H:i:s' ), current_time("timestamp")))?></td>
```
Comment (sc0ttkclark) [inline adminpages/reports/login.php:231]:
```suggestion
							<td><?php echo date_i18n( 'm/d/Y', strtotime( get_date_from_gmt( $theuser->user_registered ), current_time( 'timestamp' ) ) ); ?></td>

```

File: classes/class-pmpro-members-list-table.php [hunk 3]
```diff
@@ -574,7 +574,7 @@ public function column_joindate( $item ) {
 		if ( empty( $joindate ) ) {
 			return;
 		}
-		return date_i18n( get_option('date_format'), $joindate );
+		return date_i18n( get_option('date_format'), strtotime( get_date_from_gmt( date( 'Y-m-d H:i:s', $joindate ) ) ) );
```
Comment (sc0ttkclark) [inline classes/class-pmpro-members-list-table.php:577]:
```suggestion
		return date_i18n( get_option( 'date_format' ), strtotime( get_date_from_gmt( date( 'Y-m-d H:i:s', $joindate ) ) ) );
```

**Review by sc0ttkclark — APPROVED** [review]
