### PR TITLE
 * If the report is a "Last 12 month report" tweak start date to be t…

### LINKED ISSUE #2691: Monthly Report vs. Last 12 Months Showing Different Data
**Describe the bug**
The monthly revenue report shows data for all months in the selected year.

You can also show a leading 12 months of data. In this view, the report data for the "oldest" month is incorrect as shown in the screenshots below:

**Screenshots**
Screenshot 2023-11-28 at 7 38 02 AM

Screenshot 2023-11-28 at 7 38 15 AM

**Expected behavior**
The month "November" in both screenshots should show the same data.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by MaximilianoRicoTabo**
image
image

image
image

* [x] Have you followed the [Contributing guideline](https://github.com/strangerstudios/paid-memberships-pro/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/strangerstudios/paid-memberships-pro/pulls) for the same update/change?

Resolves #2691 
### How to test the changes in this Pull Request:

1. Generate a 12 month report
2. Observe than the first month of the report totally matches with monthly report
3. Observe than there aren't 13 bars anymore ( 11 full month and 2partials ) There are 11 full months and a partial (current month)

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### CODE REVIEW

File: adminpages/reports/sales.php [hunk 1]
```diff
@@ -274,7 +274,12 @@ function pmpro_report_sales_page()
 
 		// Set up the start and end dates.
 		$startdate   = date( 'Y-m-d', strtotime( current_time( 'mysql' ) .' -'.$timeframe.' '.$report_unit ) );
-		$enddate     = current_time( 'mysql' );
+		if ( $period === '12months' ) {
+			// Adjust $startdate to avoid partial months at the beginning the report.
+			$startdate = date( 'Y-m-d', strtotime( $startdate . ' +1 MONTH' ) );
+			$startdate = date( 'Y-m-01', strtotime( $startdate ) );
```
Comment (dparker1005) [inline adminpages/reports/sales.php:280]:
```suggestion
			$startdate = date( 'Y-m-01', strtotime( $startdate . ' +1 MONTH' ) );
```
I think this can be done in one step.

**Comment by dparker1005** [comment]
This may be a good time to split up the `} else if ( $period === '7days' || $period === '30days' || $period === '12months' ) {` into an `if` for 7 & 30 days and a separate `if` for 12 months. Previously, the setups for those 3 report types were similar, but at this point the only similarity is `$enddate = current_time( 'mysql' );`.

File: adminpages/reports/sales.php (hunk 1 above)
Comment (MaximilianoRicoTabo) [reply adminpages/reports/sales.php]: done.

File: adminpages/reports/sales.php [hunk 2]
```diff
@@ -258,33 +258,31 @@ function pmpro_report_sales_page()
...
 		$startdate   = date( 'Y-m-d', strtotime( current_time( 'mysql' ) .' -'.$timeframe.' '.$report_unit ) );
-		$enddate     = current_time( 'mysql' );
+		$enddate = current_time( 'mysql' );
+	} else if ( $period === '12months' ) {
+		$report_unit = 'MONTH';
+		$timeframe = 12;
+		$axis_date_format = 'M';
+		$tooltip_date_format = 'F Y';
+		//Set the start date to the first day of the month 11 months ago.
+		$startdate = date( 'Y-m-01', strtotime( date( 'Y-m-d', strtotime( current_time( 'mysql' ) .' -'.$timeframe.' '.$report_unit ) ). ' +1 MONTH' ) );
```
Comment (dparker1005) [inline adminpages/reports/sales.php:275]:
```suggestion
		$startdate = date( 'Y-m-01', strtotime( current_time( 'mysql' ) . ' -11 MONTH' ) );
```

**Comment by ideadude** [comment]
@kimcoleman from our chat earlier, I think "last 12 months" might more often colloquially mean "ending with the last day of last month, and showing the previous 12 months of data".

So if you asked for the "last 12 months" in the middle of February, the chart should show Feb of last year through Jan of this year.

I trust your judgement on how to configure the chart. Once you are happy with it, let me know or merge. Thanks.
