### PR TITLE
Member History and Order Timestamps Now Correlate

### LINKED ISSUE #2206: Order timestamps in Member History section are wrong.
The order timestamp doesn't match in the Member History section against the order's timestamp when viewing it in the orders table or the single order view.

**To Reproduce**
1. Go to Memberships > Orders and view an order timestamp.
2. Click on the user and navigate to the Member History section, see that the same order has a different timezone.

**Screenshots**
If applicable, please attach a screenshot to make your issue clearer.
Screen Shot 2022-08-23 at 09 36 59
Screen Shot 2022-08-23 at 09 37 09

### LINKED ISSUE #2447: Timezone Differs between Member History and Order
**Describe the bug**
The member history timestamp differs by 3 - 4 hours compared to the timestamp that is displayed on the order edit page. The order timestamp is correct as this correlates with a timestamp in Stripe according to a customer. 

**To Reproduce**
1. Edit your profile and scroll down to the Member History Section
2. Take note of the date for a specific entry
3. Click edit on that entry - the date in the order itself will be different

**Screenshots**

Member History
image

Edit Order
image

**Expected behavior**
The two timestamps should be the same

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
PMPro 2.10.3
WP 6.2
```
</details>

### PR DESCRIPTION
**Pull request by JarrydLong**
### All Submissions:

* [x] Have you followed the [Contributing guideline](https://github.com/strangerstudios/paid-memberships-pro/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/strangerstudios/paid-memberships-pro/pulls) for the same update/change?

### Changes proposed in this Pull Request:

The member history page found in the edit profile page references an invoice timestamp. This has been changed to reference the order timestamp as people expect the two to match when clicking through from the member history.

Resolves #2447
Resolves #2206

### How to test the changes in this Pull Request:

1. Edit a user profile and scroll down to the Member History Section
2. Take note of an order's timestamp, click Edit
3. The timestamp should match what you saw in member history

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

The member history and order timestamps now show as the same times

### CODE REVIEW

File: includes/profile.php [hunk 1]
```diff
@@ -416,7 +416,7 @@ function pmpro_membership_history_profile_fields( $user ) {
 	global $wpdb;
 
 	//Show all invoices for user
-	$invoices = $wpdb->get_results( $wpdb->prepare( "SELECT mo.*, UNIX_TIMESTAMP(mo.timestamp) as timestamp, du.code_id as code_id FROM $wpdb->pmpro_membership_orders mo LEFT JOIN $wpdb->pmpro_discount_codes_uses du ON mo.id = du.order_id WHERE mo.user_id = %d ORDER BY mo.timestamp DESC", $user->ID ));
+	$invoices = $wpdb->get_results( $wpdb->prepare( "SELECT mo.*, UNIX_TIMESTAMP(mo.timestamp) as timestamp, du.code_id as code_id, mo.timestamp as order_timestamp FROM $wpdb->pmpro_membership_orders mo LEFT JOIN $wpdb->pmpro_discount_codes_uses du ON mo.id = du.order_id WHERE mo.user_id = %d ORDER BY mo.timestamp DESC", $user->ID ));
```
Comment (dparker1005) [inline includes/profile.php:419]:
```suggestion
	$invoices = $wpdb->get_results( $wpdb->prepare( "SELECT mo.*, du.code_id as code_id FROM $wpdb->pmpro_membership_orders mo LEFT JOIN $wpdb->pmpro_discount_codes_uses du ON mo.id = du.order_id WHERE mo.user_id = %d ORDER BY mo.timestamp DESC", $user->ID ));
```

File: includes/profile.php [hunk 2]
```diff
@@ -462,11 +462,14 @@ function pmpro_membership_history_profile_fields( $user ) {
 					<tr>
 						<td>
 							<?php
+
+								$order_timestamp = strtotime( $invoice->order_timestamp );
+
```
Comment (dparker1005) [inline includes/profile.php:467]:
```suggestion
```

File: includes/profile.php [hunk 3]
```diff
@@ -462,11 +462,14 @@ function pmpro_membership_history_profile_fields( $user ) {
...
+								$order_timestamp = strtotime( $invoice->order_timestamp );
+								
 								echo esc_html( sprintf(
 									// translators: %1$s is the date and %2$s is the time.
 									__( '%1$s at %2$s', 'paid-memberships-pro' ),
-									esc_html( date_i18n( get_option( 'date_format' ), $invoice->timestamp ) ),
-									esc_html( date_i18n( get_option( 'time_format' ), $invoice->timestamp ) )
+									esc_html( date_i18n( get_option( 'date_format' ), $order_timestamp ) ),
+									esc_html( date_i18n( get_option( 'time_format' ), $order_timestamp ) )
```
Comment (dparker1005) [inline includes/profile.php:472]:
```suggestion
									esc_html( date_i18n( get_option( 'date_format' ), strtotime( get_date_from_gmt( $invoice->timestamp ) ) ) ),
									esc_html( date_i18n( get_option( 'time_format' ), strtotime( get_date_from_gmt( $invoice->timestamp ) ) ) )
```

**Review by dparker1005 — CHANGES_REQUESTED** [review]
I still had a timezone discrepancy on my local site between the Member History order date and the date on the Orders page. These suggestions should make the logic that we use to get the date on the Member History table exactly the same as the logic we use elsewhere

If you still see any discrepancies after applying all these suggestions, let me know and we can take a closer look together
